### ISSUE TITLE
Add rule tracing

### ISSUE THREAD

**Issue by KingSupernova31** [lunakv/academyruins#9] opened 2022-12-24 22:58 UTC
A feature that Andrew was experimenting with on VJ before it went down was a rules trace. You could enter any rule number and it would show you a history of all changes to that rule. I found it extremely useful.

**Comment by lunakv** [comment] 2022-12-25 11:26
This is on the shortlist, though the little time I have to work on AR right now is spent on finishing up the MTR parser. Closing this for now as a duplicate of https://github.com/lunakv/academyruins-api/issues/9, feel free to reopen if you have any frontend-specific notes.

**Closed as completed by lunakv** 2022-12-25 11:26 UTC

**Comment by KingSupernova31** [comment] 2022-12-25 17:26
Ah, I didn't realize there was a separate repo for the API.

I think front end it should just look similar to the diffs. Display a list of all versions of that rule on the right in reverse chronological order, and on the left of each rule, include the date of change and the name of the set that that change coincided with.
